document.write('<div id="header">');
document.write('<div class="header-wrap">');
document.write('<div class="logo"><a href="http://usnbkiqas100p/home.cfm"><img src="http://usnbkiqas100p/header/images/logo.png"  border="0"/></a></div>');
document.write('<div class="inner-header">');
document.write('<div class="main-nav">');
document.write('<ul>');
document.write('<li class="people"> <a href="#"><span class="arrow"></span>Our People</a> ');
document.write('<ul>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/EmpNews/">Employee News, Recognition &amp; Thanks</a></li>');
document.write('<li><a href="http://intranet.ul.com/ULSearch/Pages/people.aspx" >UL Associate Profile Search</a></li>');
document.write('<li><a href="http://usnbkm501.us.ul.com/gtd.nsf" target="_blank">Global Employee Directory</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/newemployees/">Welcome New Employees</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="company">');
document.write('<a href="#"><span class="arrow"></span>Our Company</a>');
document.write('<ul>');
document.write('<li class="hasChildren">');
document.write('<a href="#">Business Units</a>');
document.write('<ul>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/ProductSafety/">Product Safety</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/EnvServs/">Environment</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/LHS/">Life &amp; Health</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/KnowledgeServices/">Knowledge Services</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/VS/">Verification Services</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="hasChildren">');
document.write('<a href="#">Global Functions</a>');
document.write('<ul>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/Certification/">Certification Programs, Accreditation & Standards</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/CommercialOps/">Commercial</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/GlobalFin/">Finance</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/marketing/">Global Marketing & Strategy</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/HR/">Human Resources</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/ethics/">Ethics & Compliance</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/IT/">IT</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/Legal/">Legal</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/ethics/">Ethics & Compliance</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/history/">History</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/Leadership/">Leadership</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/mission/">Mission</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/Offices/">Office Locations</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/Acquisitions/">Acquisitions</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/epmo/">ePMO (Enterprise Roadmap)</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="career"> <a href="#"><span class="arrow"></span>Pay, Benefits &amp; Career</a> ');
document.write('<ul>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/ULBenefits/">Benefits</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/CareerDevelopment/">Career Development</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/Compensation/">Compensation</a></li>');
document.write('<li><a href="http://crm.us.ul.com/OA_HTML/US/ICXINDEX.htm" target="_blank">Oracle Self-Service</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/CareerDevelopment/Pages/Performance-Management.aspx">Performance Management</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/ULUniversity/">University</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="tools"> <a href="http://intranet.ul.com/en/Tools/Pages/Home.aspx"><span class="arrow"></span>Tools &amp; Resources</a> ');
document.write('<ul>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/Pages/Home.aspx#Applications">Operations Work Tools &amp; Resources</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/Pages/Home.aspx#comm">Communication &amp; Collaboration Tools</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/Pages/Home.aspx#personal">Personal Management Tools</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/Pages/Home.aspx">Departments &amp; Services</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/Library/Pages/Home.aspx">Library</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="community"> <a href=""><span class="arrow"></span>Community</a> ');
document.write('<ul>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/community/">Our Community</a></li>');
document.write('<li><a href="http://intranet.ul.com/en/Tools/DeptsServs/CSR/">Corporate Social Responsibility</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="ul"><a href="http://www.ul.com" target="_blank">UL.com</a></li>');
document.write('</ul>');
document.write('<form method="GET" action="http://intranet.ul.com/ULSearch/Pages/Results.aspx?" class="search" name="gs">');
document.write('<input type="hidden" name="client" value="default_frontend">');
document.write('<input type="hidden" name="output" value="xml_no_dtd">');
document.write('<input type="hidden" name="proxystylesheet" value="default_frontend">');
document.write('<input type="hidden" name="sort" value="date:D:L:d1">');
document.write('<input type="hidden" name="entqr" value="3">');
document.write('<input type="hidden" name="oe" value="UTF-8"><input type="hidden" name="ie" value="UTF-8">');
document.write('<input type="hidden" name="ud" value="1">');
document.write('<input type="hidden" name="site" value="default_collection">');
document.write('<input type="text" name="k" size="15" maxlength="256" value="" >');
document.write('<input type="image" src="http://usnbkiqas100p/header/images/search-button.png" class="button" height="16" width="16" />');
document.write('</form>');
document.write('</div>');
document.write('<div class="clearfix"></div>');
document.write('<div class="title">');
document.write('<a href="http://usnbkiqas100p/depts/itd/empnoAlternate.cfm" target="_blank"><input class="image techSupport3" type="submit" title="submit" value=""><img src="http://usnbkiqas100p/images/clear.gif" height="25" width="119" class="title_sd"></a>');
document.write('<span class="site-title">UL INTRANET</span>');
document.write('<span class="department-title"><img src="deptname.png"></span>');
document.write('</div>');
document.write('</div>');
document.write('</div>');
document.write('</div>');